config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"
  get "/categories/:id", to: "home#show"

  namespace :admin do
    get "/dashboard", to: "dashboard#index"
    resource :crawlers, only: %i(create destroy)
    resources :crawler_questions, only: %i(index create update destroy)
    resources :crawler_answers, only: %i(create update destroy)
    resources :categories, except: %i(new edit)
  end

  namespace :api do
    namespace :v1 do
      resources :exams
      resources :results
    end
  end

  devise_for :users
  resources :questions do
    resources :rollback_questions, only: :index
  end
  resources :exams
  mount ActionCable.server => '/cable'
  resources :categories, only: [:show]
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  cattr_accessor :skip_callback
  belongs_to :category
  has_many :answers, dependent: :destroy, inverse_of: :question
  has_many :results
  belongs_to :user
  has_many :notifications, dependent: :destroy

  has_paper_trail on: :update

  before_save :check_to_create_version, if: :persisted?
  after_commit :show_question, on: :create
  after_commit :update_for_question, on: :update

  accepts_nested_attributes_for :answers, allow_destroy: true, reject_if: :all_blank
  validates :level, presence: true
  validates :question_content, presence: true, length: { minimum: 5, maximum: 255 }
  validate :valid_answer, :valid_correct, :count_answer, :question_exist
  enum level: %i[easy hard]

  def self.getquestion(exam)
    hard = exam.master? ? 10 : 5
    questions = includes(:category).where(level: "hard", category_id: exam.category_id).sample(hard)
    questions += includes(:category).where(level: "easy", category_id: exam.category_id).sample(20 - hard)
    questions.shuffle
  end

  def convert_attributes(crawler_question)
    self.question_content = crawler_question.question_content
    self.level = crawler_question.level
    crawler_question.crawler_answers.each { |answer| answers.new content: answer.content, status: answer.status }
  end

  private

  def valid_correct
    correct = new_record? ? answers.select(&:status).size : answers.select { |a| a.status && !a._destroy }.size
    errors.add(:base, I18n.t("model.question.no_correct")) if correct.zero?
    errors.add(:base, I18n.t("model.question.no_wrong")) if correct == answers.collect { |a| a.content unless a._destroy }.compact.size
  end

  def count_answer
    total_answer = new_record? ? answers.size : answers.reject(&:_destroy).size
    errors.add(:base, I18n.t("model.question.less_than")) if total_answer < 2
  end

  def valid_answer
    answer = answers.collect { |a| a.content unless a._destroy }.compact
    errors.add(:base, I18n.t("model.question.not_same")) unless answer.compact.uniq.size == answer.size
  end

  def question_exist
    questions = Question.joins(:answers).where(question_content: question_content,
                                               category_id: category_id, level: level,
                                               answers: { content: answers.map { |a| a.content unless a._destroy } }).map(&:id)
    errors.add(:base, I18n.t("model.question.exist")) if new_record? && questions.present?
    return unless persisted?

    questions.delete(id)
    errors.add(:base, I18n.t("model.question.exist")) if questions.present?
  end

  def show_question
    QuestionBroadcastJob.perform_now(Notification.where(question_id: self, notification_content: 0))
  end

  def update_for_question
    skip_callback = false
    UpdateQuestionJob.perform_now(self)
  end

  def check_to_create_version
    return if skip_callback
    raise StandardError if !changed? && answers.none? { |e| e.new_record? || e.marked_for_destruction? || e.changed? }
    return if Question.where(id: id, category_id: category_id, level: level, question_content: question_content).blank?

    version = paper_trail.record_update(force: true, in_after_callback: false, is_touch: false)
    version.update_columns created_at: Time.zone.now
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :load_question, only: %i[show edit update]
  before_action :load_notification, only: :show

  def index
    @questions = Question.includes(:answers, :category).order(updated_at: :desc).page(params[:page]).per(6)
  end

  def new
    @question = Question.new
    2.times { @question.answers.build }
  end

  def create
    @question = current_user.questions.new question_params
    ActiveRecord::Base.transaction do
      @question.save!
      Notification.import!(%i[user_id question_id notification_content],
                           User.admin.ids.map { |id| [id, @question.id, 0] })
    end
  rescue StandardError
    flash.now[:danger] = t "messages.failed.questions.create"
  end

  def show
    @notification.update_all(notification_status: :seen) if @notification.not_seen.any?
    @versions = @question.versions.page(params[:page]).per(3)
  end

  def edit; end

  def update
    @question.assign_attributes question_params
    Question.skip_callback = false
    ActiveRecord::Base.transaction do
      @question.save!
      unless @question.user == current_user
        notification = Notification.create!(user_id: @question.user_id, question_id: @question.id,
                                            notification_content: 1, other_user: current_user.name)
        NotificationUpdateJob.perform_now(notification)
      end
    end
  rescue StandardError
    flash.now[:danger] = t "messages.failed.questions.create"
  end

  private

  def question_params
    params.require(:question).permit(:question_content,
                                     :level, :category_id,
                                     answers_attributes: %i[id status content _destroy])
  end

  def check_admin
    return if current_user.admin?

    raise ActionController::RoutingError, params[:path]
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def load_notification
    @notification = Notification.where(user_id: current_user.id, question_id: @question.id)
  end
end

app/views/questions/_answer.html.slim
label.label-answer style= ("color: #{answer.status == true ? 'green' : 'red'}")
  = answer.content

app/views/questions/_answer_fields.html.slim
.nested-fields.ui-state-default
  = link_to_remove_association f do
    span.fa.fa-times-circle aria-hidden="true" style="float: right; margin-right: 4px;"
  = f.text_field :content, class: "form-control"
  = f.check_box :status, id: "checkbox-answer"

app/views/questions/_form.html.slim
.modal-dialog
  .modal-content
    = form_for question, remote: true do |f|
      .modal-body
        h2.text-center = t ".question"
        #message_errors
        hr
        .form-group
          = f.label :category, class: "col-form-label"
          = f.select :category_id, options_for_select(select_category,
            selected: f.object.category_id), {include_blank: t(".choose_category")},
            {class: "form-control", required: true}
        .form-group
          = f.label :level, class: "col-form-label"
          = f.select :level, options_for_select(select_level,
            selected: f.object.level), {include_blank: t(".choose_level")},
            {class: "form-control", required: true}
        .form-group
          = f.label t(".question"), class: "col-form-label"
          = f.text_area :question_content, class: "form-control"
        #sortable
          = f.label t(".answer")
          = f.fields_for(:answers) do |answer|
            = render "answer_fields", f: answer
        .modal-footer
          = link_to_add_association t(".add_answer"), f, :answers, class: "fa fa-plus"
          = f.submit t(".submit"), class: "btn btn-primary"
          = link_to t(".cancel"), "#", class: "btn btn-danger", data: {dismiss: "modal"}

app/views/questions/_question.html.slim
tr.question
  td = link_to truncate(question.question_content, length: 17), question_path(question)
  td = question.category.name
  td = question.level.titleize
  td
    = question.updated_at > question.created_at ? t(".edit") : t(".create")
    = time_ago_in_words(question.updated_at)
  td
    button.btn.btn-info[data-toggle="collapse" data-target="#info#{question.id}"]
      em.fa.fa-eye
    button.btn.btn-warning
      em.fa.fa-pencil
    = link_to "#", method: :delete, class: "btn btn-danger", data: { confirm: "Xóa" }
      em.fa.fa-trash
tr
  td.answer[colspan="5"]
    ul id="info#{question.id}" class="collapse list-group list-group-flush"
      = render question.answers

app/views/questions/_question_content.html.slim
.card
  h5.card-header style="word-wrap: break-word;"
    = question.question_content
  .card-body.altcontainer
    = render partial: "questions/answer", collection: question.answers

app/views/questions/_version.html.slim
= tag.tr do
  = tag.td version.event.titleize, class: "item-event"
  = tag.td version.whodunnit, class: "item-user"
  = tag.td time_ago_in_words(version.created_at), class: "item-time"
  = tag.td do
    = tag.ul class: 'list-group' do
      li.list-group-item
        strong Category:
        = " #{version.reify.category.name}"
      li.list-group-item
        strong Level:
        = " #{version.reify.level}"
      li.list-group-item
        strong Question:
        = " #{version.reify.question_content}"
      li.list-group-item
        strong Answer:
        = render partial: "questions/answer", collection: version.reify(has_many: true).answers
  - if current_user ==  @question.user
    = tag.td link_to t(".rollback"), question_rollback_questions_path(@question, version: version), remote: true, class: "btn btn-success"

app/views/questions/create.js.slim
- if @question.errors.present?
  |
    $("#message_errors").html("#{j(render 'shared/error_messages', object: @question)}");
    toastr.error("#{flash.now[:danger]}");
    $(".modal").animate({scrollTop : 0},500);
- else
  |
    $("#question-modal").modal("hide");
    toastr.success("#{flash.now[:success] = t "messages.success.questions.create" }");

app/views/questions/edit.js.slim
|
  $("#question-modal").html("#{j(render 'form', question: @question)}");
  $("#question-modal").modal("show")

app/views/questions/index.html.slim
- provide(:title, t(".question"))
h1 Here
= link_to t(".add"), new_question_path, remote: true, class: "btn btn-primary fa fa-plus fa-xs"
#question-data
  table.table.table-striped.table-hover
    thead
      tr
        th scope="col" = t(".question")
        th scope="col" = t(".category")
        th scope="col" = t(".level")
        th scope="col" = t(".time")
        th.action scope="col" = t(".action")
    tbody#question
      = render @questions
  #paginate
    = paginate @questions, theme: "twitter-bootstrap-4"
#question-modal.modal.fade

app/views/questions/new.js.slim
|
  $("#question-modal").html("#{j(render 'form', question: @question)}");
  $("#question-modal").modal("show")

app/views/questions/show.html.slim
.row
  .col-md-12 style="margin-top: 10px;"
    = link_to t(".update"), edit_question_path(@question), remote: true, class: "btn btn-primary fa fa-plus fa-xs"
    .question id="question-content-#{@question.id}"
      = render "question_content", question: @question
    h2.text-center style="margin-top: 20px;" = t(".history")
    #question-history
      table.table.table-bordered.table-hover style="margin-top: 20px; background-color: #fff"
        thead.custom-th-table
          tr
            th
              = t(".event")
            th
              = t(".modifier")
            th
              = t(".modified")
            th
              = t(".change")
            th
              = t(".action")
        tbody.custom-td-table
          = render partial: "questions/version", collection: @versions
      #paginate-history
        = paginate @versions, theme: "twitter-bootstrap-4"
#question-modal.modal.fade

app/views/questions/update.js.slim
- if @question.errors.present?
  |
    $("#message_errors").html("#{j(render 'shared/error_messages', object: @question)}");
    toastr.error("#{flash.now[:danger]}");
    $(".modal").animate({scrollTop : 0},500);
- else
  |
    $("#question-modal").modal("hide");
    toastr.success("#{flash.now[:success] = t "messages.success.questions.update" }");