config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"
  get "/categories/:id", to: "home#show"

  namespace :admin do
    get "/dashboard", to: "dashboard#index"
    resource :crawlers, only: %i(create destroy)
    resources :crawler_questions, only: %i(index create update destroy)
    resources :crawler_answers, only: %i(create update destroy)
    resources :categories, except: %i(new edit)
  end

  namespace :api do
    namespace :v1 do
      resources :exams
      resources :results
    end
  end

  devise_for :users
  resources :questions do
    resources :rollback_questions, only: :index
  end
  resources :exams
  mount ActionCable.server => '/cable'
  resources :categories, only: [:show]
end

app/models/crawler_answer.rb
# frozen_string_literal: true

class CrawlerAnswer < ApplicationRecord
  belongs_to :crawler_question

  validates :content, presence: true
end

app/controllers/admin/crawler_answers_controller.rb
# frozen_string_literal: true

module Admin
  class CrawlerAnswersController < BaseController
    before_action :load_crawler_answer, only: %i[update destroy]

    def create
      @crawler_answer = CrawlerAnswer.new crawler_answer_params
      @crawler_answer.save
      respond_to do |format|
        format.js
      end
    end

    def update
      @crawler_answer.update crawler_answer_params
      respond_to do |format|
        format.js
      end
    end

    def destroy
      @crawler_answer.destroy
      respond_to do |format|
        format.js
      end
    end

    private

    def crawler_answer_params
      params.require(:crawler_answer).permit(:content, :status, :crawler_question_id)
    end

    def load_crawler_answer
      @crawler_answer = CrawlerAnswer.find_by id: params[:id]
      return if @crawler_answer

      redirect_to admin_dashboard_path
    end
  end
end

app/views/admin/crawler_answers/_crawler_answer.html.slim
li.list-group-item.d-flex.justify-content-between.align-items-center id="crawler_answer#{crawler_answer.id}"
  div
    = crawler_answer.content
    .collapse id="edit-answer#{crawler_answer.id}"
      = render "admin/crawler_answers/form", crawler_answer: crawler_answer,
        crawler_question: crawler_answer.crawler_question
    .small
      = link_to t(".delete"), admin_crawler_answer_path(crawler_answer),
        method: :delete, remote: true, data: { confirm: t(".confirm") }
      span.text-link[data-toggle="collapse" data-target="#edit-answer#{crawler_answer.id}"]
        = t(".edit")
  span.badge.badge-success.badge-pill
    - if crawler_answer.status
      em.fa.fa-check

app/views/admin/crawler_answers/_form.html.slim
= form_for [:admin, crawler_answer], remote: true do |f|
  = f.hidden_field :crawler_question_id, value: crawler_question.id
  .form-group
    = f.text_area :content, class: "form-control"
  .form-group
    = f.check_box :status
  .form-group
    = f.submit t(".save"), class: "form-control btn btn-outline-success"
  div id="message_errors_update_answer#{crawler_answer.id}"
  div id="message_errors_create_answer#{crawler_answer.id}"

app/views/admin/crawler_answers/create.js.slim
- if @crawler_answer.errors.any?
  |
    $("#message_errors_create_answer#{@crawler_answer.id}").html('#{ j render "shared/error_messages", object: @crawler_answer }');
- else
  |
    $("#info#{@crawler_answer.crawler_question.id}").prepend('#{ j render @crawler_answer }');

app/views/admin/crawler_answers/destroy.js.slim
|
  $("#crawler_answer#{@crawler_answer.id}").remove();

app/views/admin/crawler_answers/update.js.slim
- if @crawler_answer.errors.any?
  |
    $("#message_errors_update_answer#{@crawler_answer.id}").html('#{ j render "shared/error_messages", object: @crawler_answer }');
- else
  |
    $("#crawler_answer#{@crawler_answer.id}").replaceWith('#{ j render @crawler_answer }');