config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"
  get "/categories/:id", to: "home#show"

  namespace :admin do
    get "/dashboard", to: "dashboard#index"
    resource :crawlers, only: %i(create destroy)
    resources :crawler_questions, only: %i(index create update destroy)
    resources :crawler_answers, only: %i(create update destroy)
    resources :categories, except: %i(new edit)
  end

  namespace :api do
    namespace :v1 do
      resources :exams
      resources :results
    end
  end

  devise_for :users
  resources :questions do
    resources :rollback_questions, only: :index
  end
  resources :exams
  mount ActionCable.server => '/cable'
  resources :categories, only: [:show]
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  belongs_to :user
  has_many :exams
  has_many :questions

  validates :name, presence: true, uniqueness: { case_sensitive: false }

  scope :newest, -> { order created_at: :DESC }
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

module Admin
  class CategoriesController < BaseController
    before_action :load_category, only: %i[show update destroy]

    def index
      @categories = Category.newest.includes(:questions).page(params[:page]).per(10)
      @category = Category.new
    end

    def show
      @questions = @category.questions.includes(:answers)
    end

    def create
      @category = current_user.categories.new category_params
      if @category.save
        redirect_to admin_categories_path, success: (t ".success")
      else
        respond_to do |format|
          format.js
        end
      end
    end

    def update
      @category.update category_params
      respond_to do |format|
        format.js
      end
    end

    def destroy
      if @category.questions.any? || @category.exams.any?
        flash[:warning] = t ".warning"
      else
        @category.destroy
        flash[:success] = t ".success"
      end
      redirect_to admin_categories_path
    end

    private

    def category_params
      params.require(:category).permit(:name)
    end

    def load_category
      @category = Category.includes(:questions, :exams).find_by id: params[:id]
      return if @category

      redirect_to admin_categories_path
    end
  end
end

app/views/admin/categories/_category.html.slim
tr id="category#{category.id}"
  td
    = category.name
    .collapse id="edit-category#{category.id}"
      = render "form", category: category
  td
    = link_to admin_category_path(category), class: "btn btn-outline-info"
      = category.questions.size
  td
    button.btn.btn-success[data-toggle="collapse" data-target="#edit-category#{category.id}"]
      em.fa.fa-pencil
    = link_to admin_category_path(category), method: :delete,
      class: "btn btn-danger", data: { confirm: t(".confirm") }
        em.fa.fa-trash

app/views/admin/categories/_form.html.slim
= form_for [:admin, category], remote: true do |f|
  .form-group
    = f.text_field :name, class: "form-control", placeholder: t(".placeholder")
  .form-group
    = f.submit t(".save"), class: "form-control btn btn-outline-success"
  .form-group#message_errors_create
  div id="message_errors_update#{category.id}"

app/views/admin/categories/create.js.slim
|
  $("#message_errors_create").html('#{ j render "shared/error_messages", object: @category }');

app/views/admin/categories/index.html.slim
- provide(:title, t(".title"))

button.btn.btn-primary.mt-2.mb-2[data-toggle="collapse" data-target="#new-category"]
  = t ".new"

#new-category.collapse.mt-2.mb-2
  = render "form", category: @category

table.table.table-striped.table-hover
  thead
    tr
      th scope="col" = t ".category"
      th.action scope="col" = t ".questions"
      th.action scope="col" = t ".action"
  tbody
    = render @categories
#paginate
  = paginate @categories, theme: "twitter-bootstrap-4"

app/views/admin/categories/show.html.slim
- provide(:title, @category.name)

table.table.table-striped.table-hover
  thead
    tr.text-center
      th scope="col" = t ".question"
      th scope="col" = t ".level"
      th scope="col" = t ".action"
  tbody
    = render @questions

app/views/admin/categories/update.js.slim
- if @category.errors.any?
  |
    $("#message_errors_update#{@category.id}").html('#{ j render "shared/error_messages", object: @category }');
- else
  |
    $("#category#{@category.id}").replaceWith('#{ j render @category }');